apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/argo/argocd-crds
    repoURL: https://github.com/thevops/k8s-kind-lab.git
    targetRevision: demo-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: manifests/argo/argocd
    repoURL: https://github.com/thevops/k8s-kind-lab.git
    targetRevision: demo-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
