apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: live/kind/apps/
    repoURL: git@github.com:thevops/k8s-kind-lab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
