apiVersion: v2
name: kube-prometheus-stack
version: 41.9.0 # same as chart version
dependencies:
  - name: kube-prometheus-stack
    version: 41.9.0
    repository: https://prometheus-community.github.io/helm-charts
