apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-app
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: echo-app
            port:
              number: 5678
