apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds
resources:
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-probes.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
  - https://github.com/prometheus-community/helm-charts/raw/kube-prometheus-stack-41.9.0/charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
